/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package bolsaempleo;

import java.awt.Color;
import java.awt.Desktop;
import java.awt.event.MouseAdapter;
import java.awt.event.MouseEvent;
import java.io.IOException;
import java.net.URI;
import java.net.URISyntaxException;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.Arrays;
import javax.swing.JOptionPane;

/**
 *
 * @author ruben
 */
public class FormularioConfigEmail extends javax.swing.JDialog {

    /**
     * Creates new form FormularioConfigEmail
     */
    public FormularioConfigEmail(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabecera = new javax.swing.JPanel();
        panelContenido = new javax.swing.JPanel();
        titulo = new javax.swing.JLabel();
        labelCorreo = new javax.swing.JLabel();
        inputCorreo = new javax.swing.JTextField();
        labelPassword = new javax.swing.JLabel();
        inputPassword = new javax.swing.JPasswordField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelEnlace = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();
        btnGuardar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        javax.swing.GroupLayout panelCabeceraLayout = new javax.swing.GroupLayout(panelCabecera);
        panelCabecera.setLayout(panelCabeceraLayout);
        panelCabeceraLayout.setHorizontalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 20, Short.MAX_VALUE)
        );
        panelCabeceraLayout.setVerticalGroup(
            panelCabeceraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 350, Short.MAX_VALUE)
        );

        getContentPane().add(panelCabecera, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 20, 350));

        titulo.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        titulo.setText("Configuración de email");

        labelCorreo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        labelCorreo.setText("Correo electrónico:");

        inputCorreo.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        inputCorreo.setToolTipText("<html>Introduce la dirección <b>email</b> a usar<br>\npara el <b>envío de ofertas de empleo</b><br>\n* Sólo se admiten cuentas de tipo <b>GMAIL</b> u <b>OUTLOOK</b></html>");

        labelPassword.setFont(new java.awt.Font("Arial", 0, 13)); // NOI18N
        labelPassword.setText("Contraseña:");

        inputPassword.setToolTipText("<html>Introduce aquí la <b>contraseña</b> del correo electrónico");

        jLabel1.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel1.setText("* Tenga en cuenta que si usa una cuenta gmail");

        jLabel2.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel2.setText("y tiene activada la verificación en dos pasos");

        jLabel3.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel3.setText("debe crear una contraseña para la aplicación ");

        jLabel4.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        jLabel4.setText("específica desde el siguiente enlace:");

        labelEnlace.setFont(new java.awt.Font("Lucida Grande", 0, 10)); // NOI18N
        labelEnlace.setForeground(new java.awt.Color(51, 51, 255));
        labelEnlace.setText("https://support.google.com/accounts/answer/185833");

        btnCancelar.setBackground(new java.awt.Color(232, 232, 232));
        btnCancelar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnCancelar.setText("Cancelar");
        btnCancelar.setToolTipText("<html>Pulsa para </b>cancelar</b> y salir del formulario");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnGuardar.setBackground(new java.awt.Color(232, 232, 232));
        btnGuardar.setFont(new java.awt.Font("Arial", 1, 13)); // NOI18N
        btnGuardar.setText("Guardar");
        btnGuardar.setToolTipText("<html>Pulsa para <b>guardar</b> o <b>actualizar</b> los datos introducidos");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panelContenidoLayout = new javax.swing.GroupLayout(panelContenido);
        panelContenido.setLayout(panelContenidoLayout);
        panelContenidoLayout.setHorizontalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 272, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel1)
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                            .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(labelCorreo)
                                .addComponent(labelPassword))
                            .addGap(18, 18, 18)
                            .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(inputPassword, javax.swing.GroupLayout.DEFAULT_SIZE, 200, Short.MAX_VALUE)
                                .addComponent(inputCorreo)))
                        .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addComponent(labelEnlace, javax.swing.GroupLayout.PREFERRED_SIZE, 271, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(panelContenidoLayout.createSequentialGroup()
                            .addComponent(btnCancelar)
                            .addGap(25, 25, 25)
                            .addComponent(btnGuardar))))
                .addGap(27, 27, 27))
        );
        panelContenidoLayout.setVerticalGroup(
            panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelContenidoLayout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(titulo, javax.swing.GroupLayout.PREFERRED_SIZE, 49, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelCorreo)
                    .addComponent(inputCorreo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(14, 14, 14)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(labelPassword)
                    .addComponent(inputPassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addGap(5, 5, 5)
                .addComponent(jLabel2)
                .addGap(5, 5, 5)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(labelEnlace)
                .addGap(30, 30, 30)
                .addGroup(panelContenidoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnGuardar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(19, Short.MAX_VALUE))
        );

        getContentPane().add(panelContenido, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 0, 380, 350));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        this.setVisible(false);
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        System.out.println("MENSAJE: Voy a actualizar datos de email y contraseña");
        String correo, pass;
        boolean correcto=true;
        boolean modificar = actulizarDatosCorreo();
        correo = inputCorreo.getText();
        pass = new String(inputPassword.getPassword());
        if (correo.equals("")) {
            JOptionPane.showMessageDialog(null, "No puedes dejar el campo correo sin rellenar","Error", JOptionPane.WARNING_MESSAGE);
            correcto = false;
        }
        if (pass.equals("")) {
            JOptionPane.showMessageDialog(null, "No puedes dejar el campo contraseña sin rellenar","Error", JOptionPane.WARNING_MESSAGE);
            correcto = false;
        }
        // compruebo que la cuenta sea gmail o outlook
        if (!correo.contains("@gmail") && !correo.contains("@outlook")) {
            JOptionPane.showMessageDialog(null, "La cuenta de correo debe ser tipo GMAIL u OUTLOOK","Error", JOptionPane.WARNING_MESSAGE);
            correcto = false;
        }
        if (correcto) {
            if (modificar) {
                System.out.println("actulizando datos de email...");
                try {
                PreparedStatement insertarSQL;
                insertarSQL = this.bd.dameConexion().prepareStatement("UPDATE infoemail SET email = ?, password = ? WHERE id = ?");
                insertarSQL.setString(1, correo);
                insertarSQL.setString(2, pass);
                insertarSQL.setInt(3, 1);
                insertarSQL.executeUpdate();
                this.setVisible(false);
                JOptionPane.showMessageDialog(null, "Datos del correo modificados correctamente","Exito al modificar", JOptionPane.INFORMATION_MESSAGE);
                aplicacion.muestraTablaOfertas("", "", false);
            } catch(SQLException e) {
                JOptionPane.showMessageDialog(null, e.getMessage(),"Error SQL", JOptionPane.WARNING_MESSAGE);
            }
            } else {
                System.out.println("guardando datos de email...");
                try {
                    PreparedStatement insertarSQL;
                    insertarSQL = this.bd.dameConexion().prepareStatement("INSERT INTO infoemail (email,password) VALUES (?,?)");
                    insertarSQL.setString(1, correo);
                    insertarSQL.setString(2, pass);
                    insertarSQL.executeUpdate();
                    this.setVisible(false);
                    JOptionPane.showMessageDialog(null, "Datos del correo guardados correctamente", "Exito al guardar", JOptionPane.INFORMATION_MESSAGE);
                    aplicacion.muestraTablaOfertas("", "", false);
                } catch (SQLException e) {
                    JOptionPane.showMessageDialog(null, e.getMessage(), "Error SQL", JOptionPane.WARNING_MESSAGE);
                }
            }
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    
    /**
     * Prepara el formulario
     */
    void preparaForm() {
        this.setResizable(false);
        this.setTitle("Configuración de email");
        panelCabecera.setBackground(colorPanelAcciones);
        panelContenido.setBackground(colorPanelContenido);
        labelEnlace.addMouseListener(new MouseAdapter() {
            @Override
            public void mouseClicked(MouseEvent e) {
                try {

                    Desktop.getDesktop().browse(new URI("https://support.google.com/accounts/answer/185833"));

                } catch (IOException | URISyntaxException e1) {
                    e1.printStackTrace();
                }
            }
        });
    }
    
    private boolean actulizarDatosCorreo() {
        boolean esActualizar=false;
        try {
            ResultSet rs;
            PreparedStatement consulta;
            consulta = this.bd.dameConexion().prepareStatement("SELECT * FROM infoemail WHERE id = ?");
            consulta.setInt(1, 1);
            rs = consulta.executeQuery();
            if (rs.next()) {
                esActualizar=true;
                System.out.println("MENSAJE: Ya hay datos de email, debes modificar");
            } else {
                System.out.println("MENSAJE: NO hay datos de email, debes guardar");
            }
        } catch (SQLException e) {
            System.out.println("ERROR: "+e.getMessage());
        }
        return esActualizar;
    }
    
    /**
     * Coge la conexión abierta a la BD por la aplicación
     * @param con 
     */
    public void darConexionAbierta(BD con) {
        System.out.println("AVISO: Paso la conexión BD a nuevo ciclo");
        this.bd = con;
    }
    
    /**
     * Me permite pasar la ventana de la aplicación abierta
     * @param aplicacion
     */
    public void darVentanaApp(App aplicacion) {
        System.out.println("Paso la ventana de aplicación abierta");
        this.aplicacion = aplicacion;
    }
    
    // Clase APP
    private App aplicacion;

    // Clases propias
    private BD bd;
    
    // Colores de la aplicación
    Color colorPanelAcciones = new Color(85, 136, 163);
    Color colorPanelContenido = new Color(232, 232, 232);
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JTextField inputCorreo;
    private javax.swing.JPasswordField inputPassword;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel labelCorreo;
    private javax.swing.JLabel labelEnlace;
    private javax.swing.JLabel labelPassword;
    private javax.swing.JPanel panelCabecera;
    private javax.swing.JPanel panelContenido;
    private javax.swing.JLabel titulo;
    // End of variables declaration//GEN-END:variables
}
